export enum TestName {
    BROWSER = 'browser',
    CONTEXT = 'context',
    LOCATOR_NO_CHAIN = 'locator no chain',
    LOCATOR_DESCRIBE_NO_CHAIN = 'locator describe no chain',
    LOCATOR_DESCRIBE = 'locator describe',
    LOCATOR_DESCRIBE_OPTIONS = 'locator describe options',
    LOCATOR_DESCRIBE_CHAIN = 'locator describe chain',
    LOCATOR_DESCRIBE_CHAIN_HIDE = 'locator describe chain hide',
    LOCATOR_DESCRIBE_CHAIN_DESCRIBE_ONLY = 'locator describe chain describe only',
    LOCATOR_DESCRIBE_CHAIN_FILTER = 'locator describe chain filter',
    LOCATOR_DESCRIBE_CHAIN_OR = 'locator describe chain or',
    LOCATOR_EXPECT = 'locator expect',
    LOCATOR_EXPECT_OPTIONS = 'locator expect options',
    LOCATOR_EXPECT_NOT = 'locator expect not',
    CUSTOM_EXPECT_LOCATOR = 'custom expect locator',
    CUSTOM_EXPECT_LOCATOR_NOT = 'custom expect locator not',
    CUSTOM_EXPECT_STRING = 'custom expect string',
    PAGE = 'page',
    REQUEST = 'request'
}
